This might build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,157 +1,87 @@
-name: Build Geode Mod
+# borrowed from zmx/qimiko
+
+name: Build Projects
 
 on:
-  workflow_dispatch:
-    inputs:
-      build_type:
-        description: 'Build Type'
-        required: true
-        default: 'debug'
-        type: choice
-        options:
-          - release
-          - debug
+  pull_request:
   push:
     branches:
-      - "**"
+    - "1.9"
+  workflow_dispatch:
 
 jobs:
   build:
-    if: ${{ !(github.event_name == 'push' && startsWith(github.event.head_commit.message, '[nobuild]')) }}
-    strategy:
-      fail-fast: false
-
-      matrix:
-        config:
-          - name: Windows
-            # this does linux to windows cross comp
-            os: ubuntu-latest
-            target: Win64
-            # if you don't want cross comp replace it with this
-            # os: windows-latest
-            # target isnt necessary if os is windows
-
-          - name: macOS
-            os: macos-latest
-
-          - name: Android32
-            os: ubuntu-latest
-            target: Android32
-
-          - name: Android64
-            os: ubuntu-latest
-            target: Android64
-
-          - name: iOS
-            os: macos-latest
-            target: iOS
-
-    name: ${{ matrix.config.name }}
-    runs-on: ${{ matrix.config.os }}
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Set release build env var
-        run: echo "RELEASE_BUILD=$([[ \"$BUILD_TYPE\" == \"release\" ]] && echo true || echo false)" >> $GITHUB_ENV
-
-      - name: Build the mod
-        uses: hiimjasmine00/build-geode-mod@xwin
-        with:
-          bindings: kingminer7/bindings
-          bindings-ref: patch-4
-          combine: true
-          build-config: ${{ !(github.event.inputs.build_type == 'release' || (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[rel]'))) && (matrix.config.target == 'Win64' && 'RelWithDebInfo' || 'Debug') || 'Release' }}
-          export-pdb: true
-          export-symbols: true
-          target: ${{ matrix.config.target }}
-
-  package:
-    name: Package builds
-    runs-on: ubuntu-latest
-    needs: [ 'build' ]
+    runs-on: windows-latest
 
     steps:
-      - uses: geode-sdk/build-geode-mod/combine@main
-        id: build
+    - uses: actions/checkout@v4
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: build-output
-          path: ${{ steps.build.outputs.build-output }}
+    - name: Setup Geode CLI
+      uses: geode-sdk/cli/.github/actions/setup@main
+      with:
+        version: "latest"
 
-  nightly:
-    name: Create Nightly Release
-    runs-on: ubuntu-latest
-    if: ${{ !( github.event.inputs.build_type == 'release' || (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[rel]')) ) }}
-    needs: [ 'package' ]
-    permissions:
-      contents: write
+    - uses: actions/checkout@v4
+      with:
+        repository: "qimiko/geode"
+        ref: "gdps"
+        path: ${{ github.workspace }}/geode-sdk-clone
 
-    steps:
-      - uses: actions/download-artifact@v4
-        with:
-          path: './artifacts/'
+    - uses: robinraju/release-downloader@v1
+      with:
+        repository: "qimiko/geode"
+        tag: "nightly"
+        fileName: "geode-*-+(win|android32).zip"
+        out-file-path: "${{ github.workspace }}/geode-sdk-clone/bin/nightly"
+        extract: true
 
-      - name: Create Nightly Release
-        uses: andelf/nightly-release@main
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: nightly
-          name: 'Development Release'
-          body: |
-            Development release for commit ${{ github.sha }}. Built in RelWithDebInfo.
-          files: |
-            ./artifacts/build-output/*.geode
-            ./artifacts/build-output/*.pdb
-            ./artifacts/build-output/*.sym
+    - name: Load CPM cache
+      id: cache-cpm
+      uses: actions/cache@v3
+      with:
+        path: ~/cpm-cache
+        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
+        restore-keys: |
+          ${{ runner.os }}-cpm-
 
-  release:
-    name: Create Draft Release
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.build_type == 'release' || (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[rel]')) }}
-    needs: [ 'package' ]
-    permissions:
-      contents: write
+    - name: Build subprojects
+      shell: bash
+      run: 
+        current=$(pwd)
+        outdir="$current/out/"
 
-    steps:
-      - uses: actions/checkout@v4
+        rm -rf "$outdir"
+        mkdir "$outdir"
 
-      - uses: actions/download-artifact@v4
-        with:
-          path: './artifacts/'
+        build_windows () {
+            cmake -B build-windows -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -G Ninja -DGEODE_DONT_INSTALL_MODS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
+            cmake --build build-windows
+            
+            return $?
+        }
 
-      - name: Read mod version & mod id
-        id: read_version
-        run: |
-          echo "MOD_VERSION=$(jq -r '.version' mod.json)" >> $GITHUB_ENV
+        build_windows || {
+            echo "failed to build windows :("
+            exit 1
+        }
+        geode build -p android32 || {
+            echo "failed to build android :("
+            exit 1
+        }
 
-      - name: Extract changelog section
-        id: changelog
-        run: |
-          CHANGELOG_CONTENT=$(awk '
-            /^# / { 
-              if (found_first) exit; 
-              found_first = 1; 
-              next 
-            }
-            found_first { print }
-          ' changelog.md)
-          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
-          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
+        files=$(find build-android32 -name "*.geode" -type f)
+        for file in $files
+        do
+            filename=$(basename "$file")
+            geode package merge "build-android32/$filename" "build-windows/$filename"
+        done
+        cp ./build-android32/*.geode "$outdir"
+      env:
+        GEODE_SDK: ${{ github.workspace }}/geode-sdk-clone
+        CPM_SOURCE_CACHE: ~/cpm-cache
 
-      - name: Create Draft Release
-        uses: softprops/action-gh-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.MOD_VERSION }}
-          name: ${{ env.MOD_VERSION }}
-          body: |
-            ${{ env.CHANGELOG }}
-          draft: true
-          files: |
-            ./artifacts/build-output/*.geode
-            ./artifacts/build-output/*.pdb
-            ./artifacts/build-output/*.sym
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: build-results
+        path: ${{ github.workspace }}/out/
